os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
    - ARCH=x86_64 DISTRIB=debian
    - ARCH=armhf DISTRIB=debian
  global:
  - secure: UdTLt/yDPTBPFgBPX6CDZZ6rdJkpmo1LIGJl7pjUH4XW77vWv4oSbnfkz39QVOBmaRR3a9sVyg1ikMC8PH8iriE1JpnfDOCUc7mDpQr5SeA/k5Ici6Q/fSIEdg5QDZ81bJcwJY/ibGxTdWCkVNP97/kF3wy5RiAvKYaCYJajiOnOBPtGRs6H4QD1S2YjXNUZT13m3+MSK+VLqfnqX6pKXycKT9ePsZB7+L1N8KzjYkMWTkVHEHikvOw/jeaf19fMkdoZ1HtTKrrfkHSow9WSPqAgPWcE2uV1a9aRnsvYg/RfM7q4BUnTC7O3bhELjvSK7Efiv1U/xb59ldN9TQBLtMLPogo6F+5jxrs9/R+My5+cfFw6Kv9wMR+0EE8SMqUPw8ABuVmWJwWrreQbXob2kVtJSW/5J+iNGoLp/9UVgjXCG+6rR055Kewyg9GWW5vQYSmj4RmlYQn2a8zR6O0FkUes04E2LF72ui20HTk6JZwFf7HPqLCMcoEQsT80mdVpR4FSdjn7yKejsDRohmpyKes1EiWKGhvCFbRcRYOyM5DvJ/k4xrQpZOUJmWg3248YfX4uycX79HPLnSzVqWKWaxqk7EsCfsDunDQH4IbM7fqVCjZJaJBSLNw5jaah0qyS3OrcmkRNP06QhF8e4VKZeXyJfAMm9bSWg0sqcnzwhpI=
  global:
  - secure: QPC/yI+q6EdIpLwK3D78aLJrfLvsy02Kq5tnNNzhj/PhDJ1zjRdL7YDU54fviJqmrzI3XcdFESee+c/rKgLt2yJf98P7phryKxcRcoJvdpNF7HTl1rlrkeebYF4tssYqsOAhHms9I4uvY2wVFkmdDo5lJ4394hK7lwwegAL5lAZR5eHPrBNGXluYtJf8QhnuFG7u1UMzO5ThnhEJfnx0yo9r5k8Ow5viStD69ML4QbILkjgjsGBRvz4D2AkUEN+Yw2FMnJXE6Jybwiv2j3pE6rPGMeFuErXlesbeZh9eqdnxSQnGbJEEwijNwv26vUgZ4E09Iw0DVTZjmZCw3bjv1w6gjg8/FR70iRcDQR93Sbx/5Rj6p9rr1V730+dN688uR2FMSG8M76gaoc4iURTyq4q8H1w4YctQj6rA4R11FbVhRG21CxQ46Punf0mAxNCedFmtr36j+4rch6h1t3507BNynRXJ3HP2tA2vlOayHtaLk4TiC5NMKxPHJZri5JCpWIrAxTYL27hsMRIm0jwQOUTmon9FsrPgGUNLIfXH2coFhLxAhqwo3PsY3vr+rdzYci7dXlE/tcwMrOkHDcBanMQUddZWzBpSHTbHb277yzdt17D8iOBQP7cwgNdSxYBC6OryYvSJAUKVNtDSNObL78bsxY2JwEpuLc8uarrS1Wc=
  - secure: eP+QSn5VyxplbpgpRg2lPUxAaFDL9uL3MI7vh26YDdRCO7fjVmS90FbA464q9V15aK5uZmtCKiX2uVuk7NFv4ey0OIE6oLn+v37pzDdpXaKRH7J7pcQZG97y1OaCm32qzLfjpP/2Bm8hBgYquo7EMO3LBB+WqxzjRkYmG5sHrmL2Ne+eGMjGCjY97+TTF3+cR4For7MXBlFFK+CpYwrX2gLBhbW+q3fXWxPTTF1oaWVTldatuwC83xywMDda8aDySn+FVG8EhYqjUPAECo9Pa0qtVN100yxd91YF3nc/LTwsPDCk65WSX1IVbl6ypMSxRr0xw1o5WVoY0dttBcfE5g8FlZu4nTkWUaEuNAse3UnhW2usfxA96nKhBSWYmTj/NhXw1/BXxSVv1/DYA9Cn4vvv+QPOvq1Te5InP71GXOHukQ06OcvKPORvdYdTWXFhp5X4Dn0cLjVGVrBhtydBLlSAjkzMsxEaMCJL0Tsd61gjbtV+jwGn1jwnZrSk0ODwb7WqReoFG9/LYt13D9/Ga9f+SgTaecXzr+THo4ofrRnP/NZIMk28BU5zu6cM/uilhOrRag8iMAXuBmHzh3txybYuN9kMHZLc4fOr0j5WgxpfaJw+OyuwvOWfK7sUb+fqJXWf61EyKxVA8rgGzjmKTNhQfwOUOCzn/SAVdjgl7yA=
  - secure: WxdeUeidg7pEcde2Bv7swzY9l4sGZzhn2LgNiCxf2eQN9zlY61ozx+nmbFar1fHik+cJFtGWdHCeQ96Pc6Rp/1Lbg+Q9RKP9gCtEH4cbJi82XXYQpXkq0YTuopWEaQR6T/63gscuXp50esMdbYpA25G7U2vOyH8nwp2cjZ0LGorIzHNAFMo7qALvHR1twMDPY3ve766H17tAWBK1UjmzvkGeKts2KDwxlFMg5bpNM5dOs/BXPAtYzEiQ62qPOzE/zrDGd7uWZA24TfYKLoyJVESXC3p2T19d9FJSrA72kPL79qaM3V/3Jkic5n3Eox30Qd1mZKIIfCgph8XAQKMIAav0cf4/yE50WM8prK6CS6S5DdScLza3nT1OP7GMC0IQXpwcuhLD0U262HUWFPuRbqqQxy/mmV5znk5m4lktaBYE7EMcnGSJ+gaJ7OesPZW88OQSk4bjhfgYEOE1RTfc1bTRV5MJOtqU6zsCaLpjucI7b3GC/RMtH22+u1a1uhO5p4Sw4rcxOSe0v0ehtTrBotwbSt46a05Vz+yCBYsnVBZDzdGDBfeazL8+Mi14uy0EHaymToUg7yHv+zeaAG8bJhreLXFs8pZ1z4zw2SyA8j8zug6jKAVoP5+LTeekKPJg0qd8XsebwFR6lKnLGpkzFCdHSx+9XW3uDUhXxB8fwbQ=
install: true
before_script:
- docker --version
- make --version
script:
  - make ARCH=${ARCH} DISTRIB=${DISTRIB} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} DISTRIB=${DISTRIB} push
after_script:
- docker logout
- make clean
